[theme]
primaryColor = "#8a9cd6ff" # Exempel på accentfärg
backgroundColor = "#0E1117" # Den mörka bakgrunden
secondaryBackgroundColor = "#262730" # Ändra denna till en ljusare nyans för mer kontrast
textColor = "#FAFAFA"
font = "sans serif"